# Site settings
title: Open Standard Repository
email: info@cryptoconsortium.org
description: > # this means to ignore newlines until "baseurl:"
  The CryptoCurrency Certification Consortium (C4) establishes cryptocurrency
  standards that help ensure a balance of openness &amp; privacy, security &amp;
  usability, and trust & decentralization.
baseurl: "/CCSS" # the subpath of your site, e.g. /blog/
url: "https://cryptoconsortium.github.io" # the base hostname & protocol for your site
twitter_username: _CFour_
github_username:  cryptoconsortium
logo: CCSS Logo.png
org_logo: C4 Logo.png
# Build settings
markdown: kramdown
